import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        emp = new javax.swing.JButton();
        fooddetails = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("employee details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(322, 20, 140, 23);

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "e_id", "e_name", "position", "salary"
            }
        ));
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 54, 556, 109);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setText("food details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(356, 202, 98, 23);

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "food_id", "name", "Type", "price"
            }
        ));
        jScrollPane2.setViewportView(t2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(19, 231, 547, 159);

        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "c_name", "c_address", "mobile", "bill_amount"
            }
        ));
        jScrollPane3.setViewportView(t3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(19, 474, 556, 163);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setText("customer details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(338, 440, 135, 23);

        emp.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        emp.setText("retrieve emp details");
        emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empActionPerformed(evt);
            }
        });
        getContentPane().add(emp);
        emp.setBounds(610, 50, 209, 30);

        fooddetails.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fooddetails.setText("retrieve food details");
        fooddetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fooddetailsActionPerformed(evt);
            }
        });
        getContentPane().add(fooddetails);
        fooddetails.setBounds(608, 308, 209, 31);

        customer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customer.setText("retrieve customer details");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer);
        customer.setBounds(590, 490, 253, 31);

        BACK.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(351, 669, 86, 40);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 100, 200, 180);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 350, 180, 130);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 530, 220, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empActionPerformed
DefaultTableModel model=(DefaultTableModel)t1.getModel();
try
{
    Class.forName("java.sql.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/tastybites","root","shasha");
    Statement st=conn.createStatement();
    String query="SELECT *FROM employee;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        String d1=rs.getString("e_id");
        String d2=rs.getString("e_name");
        String d3=rs.getString("position");
        String d4=rs.getString("salary");
        model.addRow(new Object[]{d1,d2,d3,d4});
    }
   rs.close();
   st.close();
   conn.close();
}
        
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"SOMETHING WENT WRONG");
}
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_empActionPerformed

    private void fooddetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fooddetailsActionPerformed
DefaultTableModel model=(DefaultTableModel)t2.getModel();
try
{
    Class.forName("java.sql.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/tastybites","root","shasha");
    Statement st=conn.createStatement();
    String query="SELECT * FROM food_detail;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        String d1=rs.getString("food_id");
        String d2=rs.getString("name");
        String d3=rs.getString("type");
        String d4=rs.getString("price");
        model.addRow(new Object[]{d1,d2,d3,d4});
    }
   rs.close();
   st.close();
   conn.close();
}
        
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"SOMETHING WENT WRONG");
}
        





// TODO add your handling code here:
    }//GEN-LAST:event_fooddetailsActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
DefaultTableModel model=(DefaultTableModel)t3.getModel();
try
{
    Class.forName("java.sql.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/tastybites","root","shasha");
    Statement st=conn.createStatement();
    String query="SELECT * FROM customer;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        String d1=rs.getString("c_name");
        String d2=rs.getString("c_address");
        String d3=rs.getString("mobile");
        String d4=rs.getString("bill_amount");
        model.addRow(new Object[]{d1,d2,d3,d4});
    }
   rs.close();
   st.close();
   conn.close();
}
        
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"SOMETHING WENT WRONG");
}
        
        














// TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
options op=new options();
 op.setVisible(true);
 this.setVisible(false);
        

// TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton customer;
    private javax.swing.JButton emp;
    private javax.swing.JButton fooddetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable t1;
    private javax.swing.JTable t2;
    private javax.swing.JTable t3;
    // End of variables declaration//GEN-END:variables
}
