
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class modify_food extends javax.swing.JFrame {

    /**
     * Creates new form modify_food
     */
    public modify_food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel5 =new javax.swing.JLabel();
        jLabel6 =new javax.swing.JLabel();
        jLabel8 =new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("  food_id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 90, 70, 19);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 160, 38, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 220, 30, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 290, 36, 19);
        getContentPane().add(tf1);
        tf1.setBounds(340, 80, 170, 40);
        getContentPane().add(tf2);
        tf2.setBounds(340, 140, 170, 40);
        getContentPane().add(tf3);
        tf3.setBounds(338, 210, 170, 40);
        getContentPane().add(tf4);
        tf4.setBounds(338, 280, 170, 40);

        update.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(70, 420, 115, 29);

        reset.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        reset.setText("RESET ");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(250, 420, 101, 29);

        back.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(440, 420, 89, 29);

        next.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(590, 420, 87, 29);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel5.setText("  UPDATE FOOD ITEM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 30, 210, 17);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 20, 260, 370);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 60, 200, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
tf1.setText(" ");
tf2.setText(" ");
tf3.setText(" ");       
tf4.setText(" ");

// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
food_list fl=new food_list();
    fl.setVisible(true);
    this.setVisible(false);
        

// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
String food_id=tf1.getText();
String name=tf2.getText();
String type=tf3.getText();
String price=tf3.getText();
int modify=JOptionPane.showConfirmDialog(this,"ARE YOU SURE TO UPDATE"+" "+food_id);
if(modify==JOptionPane.YES_OPTION)
    try
{
     Class.forName("java.sql.Driver");
      Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/tastybites","root","shasha");
       Statement st=conn.createStatement();
       String query="UPDATE food_detail SET price='"+price+"'"+"WHERE food_id='"+food_id+"'AND name='"+name+"';";
       st.executeUpdate(query);
       JOptionPane.showMessageDialog(this,"RECORD UPDATED SUCCESSFULLY"); 
}
  catch(Exception e)
  {
     JOptionPane.showMessageDialog(this,"UNSUCCESSFULL!! TRY AGAIN"); 
  }

// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
delete del=new delete();
   del.setVisible(true);
    this.setVisible(false);
        

// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify_food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton next;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
